using Chatison.Entities;
using Chatison.Utilities;
using System.Collections.Generic;

namespace Chatison.Factory
{
    public class MobileProviderFactory
    {
        public static IEnumerable<MobileProvider> CreateSeedProviders()
        {
            var mobileProviders = new List<MobileProvider>
            {
                new MobileProvider { Id = 1, Name ="3 River Wireless", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 2, Name ="7-11 Speakout (USA GSM)", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 3, Name ="Advantage Communications", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 4, Name ="AIO Wireless", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 5, Name ="Airtel (Karnataka, India)", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 6, Name ="Airtel Wireless (Montana, USA)", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 7, Name ="AirVoice", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 8, Name ="Alaska Communications Systems", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 9, Name ="Alltel", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 10, Name ="Aql", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 11, Name ="Arch Wireless", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 12, Name ="Assurance Wireless", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 13, Name ="AT&T", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 14, Name ="AT&T Enterprise Paging", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 15, Name ="BeeLine GSM (Russia)", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 16, Name ="Bell Mobility & Solo Mobile (Canada)", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 17, Name ="BigRedGiant Mobile Solutions", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 18, Name ="Bluegrass Cellular", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 19, Name ="Boost Mobile", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 20, Name ="BPL Mobile (Mumbai, India)", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 21, Name ="CallPlus", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 22, Name ="Carolina Mobile Communications", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 23, Name ="Cellular One (Dobson)", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 24, Name ="Centennial Wireless", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 25, Name ="Cingular", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 26, Name ="Claro (Brasil)", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 27, Name ="Claro (Nicaragua)", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 28, Name ="Comcel", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 29, Name ="Consumar Cellular", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 30, Name ="Credo", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 31, Name ="Cricket", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 32, Name ="C-Spire Wireless", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 33, Name ="CTI", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 34, Name ="Emtel (Mauritius)", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 35, Name ="Fido (Canada)", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 36, Name ="General Communications Inc.", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 37, Name ="Globalstar (satellite)", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 38, Name ="Golden Telecom", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 39, Name ="Google FI", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 40, Name ="H2O Wireless", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 41, Name ="Helio", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 42, Name ="Houston Cellular", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 43, Name ="Idea India", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 44, Name ="Illinois Valley Cellular", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 45, Name ="Iridium (satellite)", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 46, Name ="Iusacell", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 47, Name ="I wireless", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 48, Name ="Koodo Mobile (Canada)", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 49, Name ="Kyivstar", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 50, Name ="Lebanon MTC", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 51, Name ="LMT (Latvia)", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 52, Name ="MCI Phone", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 53, Name ="Meteor (Ireland)", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 54, Name ="MetroPCS", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 55, Name ="Midwest Wireless", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 56, Name ="MobiPCS (Hawaii only)", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 57, Name ="Mobitel (Sri Lanka)", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 58, Name ="Morris Wireless", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 59, Name ="Movicom (Argentina)", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 60, Name ="Movistar (Colombia)", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 61, Name ="MTN Ghana", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 62, Name ="MTN (South Africa)", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 63, Name ="MTS (Canada)", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 64, Name ="NET10", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 65, Name ="Nextel", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 66, Name ="NPI Wireless", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 67, Name ="Ntelos", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 68, Name ="Omnipoint", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 69, Name ="Pacific Bell", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 70, Name ="Page Plus", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 71, Name ="Personal (Argentina)", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 72, Name ="President’s Choice (Canada)", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 73, Name ="Primtel (Russia)", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 74, Name ="Qualcomm", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 75, Name ="Qwest", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 76, Name ="Republic Wireless", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 77, Name ="Revol", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 78, Name ="Rogers (Canada)", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 79, Name ="Sasktel (Canada)", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 80, Name ="SCS-900 (Russia)", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 81, Name ="Simple Freedom", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 82, Name ="Simple Mobile", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 83, Name ="SL Interactive (Australia)", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 84, Name ="Sprint", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 85, Name ="Straight Talk", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 86, Name ="Suncom", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 87, Name ="Telus Mobility (Canada)", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 88, Name ="Thumb Cellular", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 89, Name ="T-Mobile", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 90, Name ="T-Mobile (Austria)", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 91, Name ="T-Mobile (UK)", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 92, Name ="Tracfone (prepaid)", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 93, Name ="Triton", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 94, Name ="UMC (Ukraine)", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 95, Name ="Unicel", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 96, Name ="Uraltel (Russia)", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 97, Name ="US Cellular", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 98, Name ="Verizon Wireless", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 99, Name ="Vessotel (Russia)", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 100, Name ="Viaero Wireless", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 101, Name ="Virgin Mobile (Canada)", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 102, Name ="Virgin Mobile USA", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 103, Name ="Vodacom (South Africa)", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 104, Name ="Vodafone (Italy)", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 105, Name ="Western Wireless", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 106, Name ="Wind Mobile", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 107, Name ="Wyndtell", Status = Constants.RecordStatus.Active },
                new MobileProvider { Id = 108, Name ="YCC", Status = Constants.RecordStatus.Active }

            };

            return mobileProviders;
        }
    }
}
